#
# CSE183 Assignment 9 Backend
#

openapi: '3.0.3'

info:
  description: CSE183 Assignment 9 Backend
  version: 0.1.0
  title: CSE183 Assignment 9 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /user:
    get:
      parameters:
        - in: query
          name: email
          schema:
            type: string
          description: Logged in user
      responses:
        200:
          description: User data response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /mail:
    get:
      parameters:
        - in: query
          name: mailbox
          schema:
            type: string
          description: Which mailbox to return
      description: Returns all Email
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailsResponse'
        404:
          description: Mailbox cannot be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Send email to other user in the system
      requestBody:
        description: Updated email
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SentEmail'
      responses:
        200:
          description: Successfully sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        404:
          description: User cannot be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /mailboxes:
    get:
      description: Returns all mailboxes and number of unread emails
      responses:
        200:
          description: Mailboxes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mailboxes'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /mail/{id}:
    post:
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: Numeric ID of the user to get
      description: Update an existing email
      requestBody:
        description: Updated email
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        200:
          description: Email Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        404:
          description: Mailbox cannot be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Mailboxes:
      type: array
      items:
        $ref: '#/components/schemas/Mailbox'
    Mailbox:
      type: object
      properties:
        mailbox:
          type: string
        emails:
          type: integer
    Success:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    EmailsResponse:
      type: array
      items:
        $ref: '#/components/schemas/Email'
    SentEmail:
      type: object
      properties:
        from:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        subject:
          type: string
        content:
          type: string
      required:
        - from
        - to
        - subject
        - content
    Email:
      type: object
      properties:
        mailbox:
          type: string
        id:
          type: string
          format: uuid
        from:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        subject:
          type: string
        sent:
          type: string
          format: date-time
        received:
          type: string
          format: date-time
        content:
          type: string
        starred:
          type: boolean
        unread:
          type: boolean
      required:
        - id
        - from
        - to
        - subject
        - sent
        - received
        - starred
        - unread
    User:
      properties:
        email:
          type: string
          format: email
        profilePicture:
          type: string
          format: uri
        name:
          type: string
        showAvatar:
          type: boolean
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

security:
  - bearerAuth: []         # use the same name as above
