
-- Populate Your Tables Here --
INSERT INTO mail(mailbox, mail, starred) VALUES ('Sent','{"to":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"from":{"name":"CSE183 Student","email":"cse183student@ucsc.edu"},"received":"2020-11-17T23:17:19Z","sent":"2020-11-14T17:09:17Z","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","subject":"Sent sent sent"}', true);

INSERT INTO mail(mailbox, mail, starred) VALUES ('Inbox','{"to":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"from":{"name":"CSE183 Student","email":"cse183student@ucsc.edu"},"received":"2020-11-17T23:17:19Z","sent":"2020-11-14T17:09:17Z","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","subject":"Inbox inbox inbox"}', true);

INSERT INTO mail(mailbox, mail, starred) VALUES ('Trash','{"to":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"from":{"name":"CSE183 Student","email":"cse183student@ucsc.edu"},"received":"2020-11-17T23:17:19Z","sent":"2020-11-14T17:09:17Z","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","subject":"Trash trash trash"}', true);

INSERT INTO mail(mailbox, mail, starred) VALUES ('Custom Inbox 1','{"to":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"from":{"name":"Kira Gabriel","email":"cse183student@ucsc.edu"},"received":"2020-12-17T23:17:19Z","sent":"2020-11-14T17:09:17Z","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","subject":"Trash trash trash"}', true);

INSERT INTO mail(mailbox, mail, starred) VALUES ('Custom Inbox 2','{"to":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"from":{"name":"Pete Heidler","email":"cse183student@ucsc.edu"},"received":"2019-11-17T23:17:19Z","sent":"2020-11-14T17:09:17Z","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","subject":"Trash trash trash"}', true);

INSERT INTO mail(mailbox, mail, starred) VALUES ('Custom Inbox 2','{"to":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"from":{"name":"Boone Mayer","email":"cse183student@ucsc.edu"},"received":"2016-11-17T23:17:19Z","sent":"2020-11-14T17:09:17Z","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","subject":"Trash trash trash"}', true);

INSERT INTO mail(mailbox, mail, starred) VALUES ('Custom Inbox 1','{"to":{"name":"Shandra Rheam","email":"srheam0@myspace.com"},"from":{"name": "Someone else","email":"cse183student@ucsc.edu"},"received":"2020-10-17T23:17:19Z","sent":"2020-11-14T17:09:17Z","content":"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","subject":"Trash trash trash"}', true);
